name: "Comment Emoji"
description: "A Github Action, to convert your text comments to emoji rich message."
inputs:
  GITHUB_TOKEN:
    description: "GITHUB ACCESS TOKEN"
    required: true
runs:
  using: "node12"
  main: "index.js"
